### ISSUE TITLE
Conditional media (plex_recently_added) no posters

### ISSUE THREAD

**Issue by webcamleif** [matt8707/ha-fusion#481] opened 2024-05-27 19:33 UTC
I am running the latest Home Assistant, and been using your older dashboard for years and I love it.
Playing around with this one, but I cannot get the movies/series posters to show in the conditional media object.

It used to work, but I updated to the latest version of Home Assistant, and also to the latest version of plex_recently_added (https://github.com/custom-components/sensor.plex_recently_added) integration, I can see the images fine in the old dashboard but I cannot see them in ha-fusion.

Looking at the network inspection in chrome I can see it gives me a 404 and it points to:
http://IP_OF_HA_FUSION:5050/plex_recently_added?path=/library/metadata/19121/art/1716647748

If I change IP_OF_HA_FUSION to my HA instance, I can see the posters.
Any idea what has happened here?

**Comment by matt8707** [comment] 2024-05-28 05:07
Hey,

Here's some history:

Two years ago, [maykar](https://github.com/maykar) archived the `plex_recently_added` repository on GitHub, which automatically removed it from HACS. [NemesisRE](https://github.com/NemesisRE/sensor.plex_recently_added) then forked it to so it could still be easily installed. Recently, [mkanet](https://github.com/custom-components/sensor.plex_recently_added) took over the original repository and added new features.

I've noticed some issues when using it for a minute:

- Setting max to 1 returns the recently added items for each library, whereas the old behavior returned only the single most recently added item.
- There's no image resolution option, so you're essentially fetching a wallpaper-sized image each time you refresh the page.
- Instead of saving the image to `/www`, it now fetches the image from `/plex_recently_added?...`, which is not proxied in Fusion.

The fork by [NemesisRE](https://github.com/NemesisRE/sensor.plex_recently_added) still works fine and can be installed via HACS.

Here's my configuration:

```yaml
sensor:
  - platform: plex_recently_added
    host: !secret nas_host
    port: !secret plex_port
    token: !secret plex_token
    max: 1
    img_dir: /
    image_resolution: 800
```

**Comment by webcamleif** [comment] 2024-05-28 05:37
Yeah I figured all this, but I seemed to have some problems with latest version of Home Assistant and NemesisRE version (which I have been using all along prior). Which version of HA are you running?

**Comment by matt8707** [comment] 2024-05-28 05:39
2024.5.5

**Comment by webcamleif** [comment] 2024-05-28 05:59
Alright yeah I am running the same version. But for some reason when using NemesisRE:s fork, it just does not fetch any data.

My config looks about the same:
sensor:
  - platform: plex_recently_added
    host: !secret plex_host
    port: !secret plex_port
    token: !secret plex_token
    ssl: true
    max: 1
    img_dir: /
    image_resolution: 900
    
Only different is the ssl variable, which I think I need since I cant reach my plex host without tls, but it should not be a problem this has been working for 2 years prior. I'll try to dig deeper.

**Comment by webcamleif** [comment] 2024-05-28 18:54
Definitely some weird issues surrounding my installation, but I just cant figure it out.

So I got it working, but I had to point towards a external domain name, which has a valid (and trusted) certificate.
This has never been an issue prior, but something must have happened during upgrading.

I have the exact same problem with the mkanet release (which I have a ticket for btw) where it does not matter if I untick the "Verify SSL" box, it still tries to verify the certificate given to you by plex remote access feature. Which is weird, I have never had this problem before.

**Comment by matt8707** [comment] 2024-05-29 15:29
Thanks for the update. Since the issue is on your side, I'm closing this.

**Closed by matt8707** 2024-05-29 15:29 UTC

**Comment by webcamleif** [comment] 2024-05-31 05:54
If someone else struggles with this in the future I would like to add that this was caused by a locked pip package from another integration to a specific version, more specifically aiofiles. After removing that it started working again.
