### ISSUE TITLE
FR: additional attributes

### ISSUE THREAD

**Issue by t0bse** [matt8707/ha-fusion#236] opened 2024-01-22 07:56 UTC
I would like to have the attribute additional to the mode setting
So for example you could see the current temperature and the target temperature.
maybe also with suffix and prefix like in my FR #235 

![image](https://github.com/matt8707/ha-fusion/assets/45834518/2987d027-642e-48a0-8b9a-918c45ea5f94)

**Comment by matt8707** [comment] 2024-01-22 18:08
duplicate of https://github.com/matt8707/ha-fusion/issues/209

**Closed** 2024-02-10 14:55 UTC
Labels: duplicate
